# Generated by Django 2.2.9 on 2020-06-29 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chamados', '0021_auto_20200626_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='JustificativaAusencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(verbose_name='Data de Início')),
                ('data_fim', models.DateTimeField(verbose_name='Data de Fim')),
                ('tipo_de_ausencia', models.CharField(choices=[('Falta', 'Falta'), ('Atraso', 'Atraso'), ('Saída Antecipada', 'Saida Antecipada'), ('Saída Intermediária', 'Saída Intermediária')], max_length=18, verbose_name='Tipo de Ausência')),
                ('justificativa', models.CharField(choices=[('Débido em Banco de HS', 'Débido em Banco de HS'), ('Descanso de Jornadas', 'Descanso de Jornadas'), ('Serviço Externo', 'Serviço Externo'), ('Viagem à Trabalho', 'Viagem à Trabalho'), ('Treinamento Externo', 'Treinamento Externo'), ('Folga TRE', 'Folga TRE')], max_length=19, verbose_name='Justificativa')),
                ('observacao', models.TextField(max_length=250, verbose_name='Observação')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='justificativa_ausencia', to='chamados.Ticket', verbose_name='Ticket')),
            ],
        ),
    ]
