# Generated by Django 2.2.9 on 2020-06-29 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0002_auto_20200629_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='justificativaausencia',
            name='justificativa',
            field=models.CharField(choices=[('Débido em Banco de HS', 'Débido em Banco de HS'), ('Descanso de Jornadas', 'Descanso de Jornadas'), ('Serviço Externo', 'Serviço Externo'), ('Viagem à Trabalho', 'Viagem à Trabalho'), ('Treinamento Externo', 'Treinamento Externo'), ('Folga TRE', 'Folga TRE')], max_length=20, verbose_name='Justificativa'),
        ),
    ]
