# Generated by Django 2.2.9 on 2020-06-29 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0023_customlogentry'),
        ('formularios', '0004_auto_20200629_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='justificativaausencia',
            name='funcionario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='justificativa_ausencia', to='perfil.Funcionario'),
            preserve_default=False,
        ),
    ]
