# Generated by Django 2.2.9 on 2020-06-29 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0005_justificativaausencia_funcionario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='justificativaausencia',
            options={'verbose_name': 'Justificativa de Ausência', 'verbose_name_plural': 'Justificativas de Ausências'},
        ),
    ]
