# Generated by Django 2.2.9 on 2020-07-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0006_auto_20200629_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='justificativaausencia',
            name='observacao',
            field=models.TextField(max_length=250, null=True, verbose_name='Observação'),
        ),
    ]
