# Generated by Django 2.2.9 on 2020-07-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0007_auto_20200702_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='justificativaausencia',
            name='observacao',
            field=models.TextField(blank=True, default=1, max_length=250, verbose_name='Observação'),
            preserve_default=False,
        ),
    ]
