# Generated by Django 3.0.4 on 2020-04-07 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='perfil.Unidade')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('re_funcionario', models.CharField(max_length=5, verbose_name='RE')),
                ('nome', models.CharField(max_length=55, verbose_name='Nome do Funcionário')),
                ('centro_de_custo', models.CharField(max_length=10)),
                ('ramal', models.CharField(max_length=4, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Funcionário')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funcionarios', to='perfil.Unidade')),
            ],
            options={
                'unique_together': {('re_funcionario', 'unidade')},
            },
        ),
    ]
