# Generated by Django 3.0.4 on 2020-06-05 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('re_funcionario', models.CharField(max_length=9, verbose_name='RE')),
                ('nome', models.CharField(max_length=55, verbose_name='Funcionário :')),
                ('centro_de_custo', models.CharField(max_length=10)),
                ('ramal', models.CharField(blank=True, max_length=9, null=True, verbose_name='Ramal')),
                ('telefone', models.CharField(blank=True, max_length=11, verbose_name='Telefone')),
                ('email_corporativo', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Corporativo')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Pessoal')),
                ('primeiro_acesso', models.BooleanField(default=True, verbose_name='Primeiro Acesso')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funcionarios', to='perfil.Unidade')),
                ('usuario', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('re_funcionario', 'unidade')},
            },
        ),
    ]
