# Generated by Django 3.0.4 on 2020-05-27 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('re_funcionario', models.CharField(max_length=9, verbose_name='RE')),
                ('nome', models.CharField(max_length=55, verbose_name='Funcionário :')),
                ('cpf', models.CharField(blank=True, max_length=11, null=True, verbose_name='CPF')),
                ('centro_de_custo', models.CharField(max_length=10)),
                ('ramal', models.CharField(max_length=9, null=True, verbose_name='Telefone / Ramal')),
                ('email_corporativo', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Corporativo')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Pessoal')),
            ],
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcionario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to='perfil.Funcionario')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='perfil.Unidade')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='funcionario',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funcionarios', to='perfil.Unidade'),
        ),
        migrations.AlterUniqueTogether(
            name='funcionario',
            unique_together={('re_funcionario', 'unidade')},
        ),
    ]
