# Generated by Django 3.0.4 on 2020-04-07 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='perfil',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='funcionarios', to='perfil.Perfil'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='funcionario',
            unique_together={('re_funcionario',)},
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='unidade',
        ),
    ]
