# Generated by Django 3.0.4 on 2020-05-19 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_funcionario_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='nome',
            field=models.CharField(max_length=55, verbose_name='Funcionário :'),
        ),
    ]
