# Generated by Django 3.0.4 on 2020-04-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_auto_20200428_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='ramal',
            field=models.CharField(max_length=9, null=True, verbose_name='Telefone / Ramal'),
        ),
    ]
