# Generated by Django 2.2.9 on 2020-06-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_auto_20200608_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='admissao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Admissão : '),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='demissao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Demissão : '),
        ),
    ]
