# Generated by Django 3.0.4 on 2020-04-08 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_auto_20200407_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funcionario', to='perfil.Perfil'),
        ),
    ]
