# Generated by Django 3.0.4 on 2020-04-08 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0004_auto_20200408_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='perfil',
        ),
        migrations.AddField(
            model_name='perfil',
            name='funcionario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='funcionario', to='perfil.Funcionario'),
        ),
    ]
