# Generated by Django 3.0.4 on 2020-05-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0004_auto_20200529_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(max_length=11, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email Pessoal'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='email_corporativo',
            field=models.EmailField(max_length=254, verbose_name='Email Corporativo'),
        ),
    ]
