# Generated by Django 3.0.4 on 2020-06-16 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0005_auto_20200615_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAutizacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atualizacao', models.DateField(auto_now_add=True, verbose_name='Atualização')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='perfil.Funcionario')),
            ],
        ),
    ]
