# Generated by Django 3.0.4 on 2020-05-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0006_auto_20200529_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(blank=True, default=1, max_length=11, verbose_name='CPF'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='email',
            field=models.EmailField(blank=True, default=1, max_length=254, verbose_name='Email Pessoal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='email_corporativo',
            field=models.EmailField(blank=True, default=1, max_length=254, verbose_name='Email Corporativo'),
            preserve_default=False,
        ),
    ]
