# Generated by Django 3.0.4 on 2020-06-16 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0006_registroautizacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registroautizacao',
            options={'verbose_name': 'Registro de Autorizações', 'verbose_name_plural': 'Registro de Autorizações'},
        ),
    ]
