# Generated by Django 3.0.4 on 2020-06-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0007_auto_20200616_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroautizacao',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Atualização'),
        ),
    ]
