# Generated by Django 3.0.4 on 2020-06-16 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0008_auto_20200616_1252'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegistroAutizacao',
            new_name='RegistroAutorizacao',
        ),
    ]
