# Generated by Django 3.0.4 on 2020-05-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0009_auto_20200529_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email Pessoal'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='email_corporativo',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email Corporativo'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='ramal',
            field=models.CharField(blank=True, max_length=9, verbose_name='Ramal'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='telefone',
            field=models.CharField(blank=True, max_length=11, verbose_name='Telefone'),
        ),
    ]
