# Generated by Django 3.0.4 on 2020-06-16 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0009_auto_20200616_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroautorizacao',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='perfil.Funcionario'),
        ),
    ]
