# Generated by Django 3.0.4 on 2020-06-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0011_auto_20200529_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='ramal',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='Ramal'),
        ),
    ]
