# Generated by Django 3.0.4 on 2020-06-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0012_auto_20200616_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroautorizacao',
            name='acao',
            field=models.CharField(choices=[(1, 'Alteração'), (2, 'Exclusão')], default=1, max_length=9),
        ),
    ]
