# Generated by Django 3.0.4 on 2020-06-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0012_auto_20200601_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Pessoal'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='email_corporativo',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Corporativo'),
        ),
    ]
