# Generated by Django 3.0.4 on 2020-06-16 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0013_registroautorizacao_acao'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='termo_dados',
            field=models.BooleanField(default=False),
        ),
    ]
