# Generated by Django 3.0.4 on 2020-06-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0015_auto_20200602_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='primeiro_acesso',
            field=models.BooleanField(default=False, verbose_name='Primeiro Acesso'),
        ),
    ]
