# Generated by Django 3.0.4 on 2020-06-16 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0016_auto_20200616_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='termo_dados',
            field=models.CharField(choices=[('1', 'Alteração'), ('2', 'Exclusão')], max_length=9, verbose_name='Termo de Consentimento'),
        ),
        migrations.AlterField(
            model_name='registroautorizacao',
            name='acao',
            field=models.CharField(choices=[('1', 'Alteração'), ('2', 'Exclusão')], default=1, max_length=9, verbose_name='Ação'),
        ),
    ]
