# Generated by Django 3.0.4 on 2020-06-03 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0018_auto_20200602_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='primeiro_acesso',
            field=models.BooleanField(default=True, verbose_name='Primeiro Acesso'),
        ),
    ]
