# Generated by Django 3.0.4 on 2020-06-16 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0018_auto_20200616_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='termo_dados',
            field=models.CharField(blank=True, choices=[('1', 'Alteração'), ('2', 'Exclusão')], max_length=9, verbose_name='Termo de Consentimento'),
        ),
    ]
