# Generated by Django 2.2.9 on 2020-06-17 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0019_auto_20200616_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroautorizacao',
            name='campos',
            field=models.CharField(default=2, max_length=50, verbose_name='Status de campo'),
            preserve_default=False,
        ),
    ]
