# Generated by Django 2.2.9 on 2020-06-18 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0020_registroautorizacao_campos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='termo_dados',
            field=models.CharField(blank=True, choices=[('Alteração', 'Alteração'), ('Exclusão', 'Exclusão'), ('Alteração / Exclusão', 'Alteração / Exclusão')], max_length=9, verbose_name='Termo de Consentimento'),
        ),
        migrations.AlterField(
            model_name='registroautorizacao',
            name='acao',
            field=models.CharField(choices=[('Alteração', 'Alteração'), ('Exclusão', 'Exclusão'), ('Alteração / Exclusão', 'Alteração / Exclusão')], default=1, max_length=9, verbose_name='Ação'),
        ),
    ]
