# Generated by Django 2.2.9 on 2020-06-18 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0021_auto_20200617_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='termo_dados',
            field=models.CharField(blank=True, choices=[('Alteração', 'Alteração'), ('Exclusão', 'Exclusão')], max_length=9, verbose_name='Termo de Consentimento'),
        ),
        migrations.DeleteModel(
            name='RegistroAutorizacao',
        ),
    ]
