# Generated by Django 2.2.9 on 2020-07-24 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0023_customlogentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroDeCusto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=12, unique=True, verbose_name='Número Centro de Custo')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Centro de Custo')),
                ('responsaveis', models.CharField(max_length=250, null=True, verbose_name='Responsaveis')),
            ],
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='centro_de_custo',
            field=models.CharField(max_length=12, verbose_name='Centro de Custo'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='centro_de_custo_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='perfil.CentroDeCusto', verbose_name='Centro de Custo'),
        ),
    ]
