# Generated by Django 2.2.9 on 2020-07-24 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0024_auto_20200724_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='centrodecusto',
            name='responsaveis',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Responsaveis'),
        ),
    ]
