# Generated by Django 2.2.9 on 2020-07-21 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0024_centrodecusto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centrodecusto',
            name='responsaveis',
            field=models.ManyToManyField(blank=True, related_name='funcionarios', to='perfil.Funcionario'),
        ),
    ]
