# Generated by Django 2.2.9 on 2020-07-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0025_auto_20200724_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centrodecusto',
            name='responsaveis',
            field=models.CharField(default=1, max_length=250, verbose_name='Responsaveis'),
            preserve_default=False,
        ),
    ]
