# Generated by Django 2.2.9 on 2020-07-25 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0025_auto_20200724_2157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='centro_de_custo_link',
            new_name='centro_de_custo',
        ),
    ]
