# Generated by Django 2.2.9 on 2020-07-24 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0025_centrodecusto_responsaveis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centrodecusto',
            name='responsaveis',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Responsavei CharField'),
        ),
    ]
