# Generated by Django 2.2.9 on 2020-07-25 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0026_auto_20200724_2159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='centro_de_custo',
            new_name='centro_de_custo_link',
        ),
    ]
