# Generated by Django 2.2.9 on 2020-07-24 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0028_auto_20200724_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='centro_de_custo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='perfil.CentroDeCusto', verbose_name='Centro de Custo CDC'),
        ),
    ]
