# Generated by Django 2.2.9 on 2020-07-28 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0028_funcionario_centro_de_custo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='centro_de_custo',
        ),
    ]
