# Generated by Django 2.2.9 on 2020-08-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0030_funcionario_espelho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='espelho',
            field=models.ImageField(default='0000.JPG', max_length=200, upload_to='espelhos', verbose_name='Fotos Funcionários'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='telefone',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='Telefone'),
        ),
    ]
