# Generated by Django 2.2.9 on 2020-08-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('perfil', '0031_auto_20200805_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Acesso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.ForeignKey(on_delete='Grupo', to='auth.Group')),
                ('item', models.ForeignKey(on_delete='Item', to='perfil.Item')),
                ('unidade', models.ForeignKey(on_delete='Unidade', to='perfil.Unidade')),
            ],
        ),
    ]
