# Generated by Django 2.2.9 on 2020-08-10 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('perfil', '0032_acesso_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acesso',
            name='grupo',
        ),
        migrations.AddField(
            model_name='acesso',
            name='grupo',
            field=models.ManyToManyField(related_name='Grupo', to='auth.Group'),
        ),
        migrations.RemoveField(
            model_name='acesso',
            name='unidade',
        ),
        migrations.AddField(
            model_name='acesso',
            name='unidade',
            field=models.ManyToManyField(related_name='Unidade', to='perfil.Unidade'),
        ),
    ]
