# Generated by Django 2.2.9 on 2020-08-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0033_auto_20200810_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidade',
            name='email',
            field=models.EmailField(default='', max_length=250, verbose_name='E-mail'),
        ),
    ]
