# Generated by Django 2.2.9 on 2020-08-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0035_auto_20200825_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidade',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=250, verbose_name='E-mail'),
        ),
    ]
