# Generated by Django 2.2.9 on 2020-08-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('perfil', '0036_auto_20200825_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidade',
            name='grupo',
            field=models.ManyToManyField(to='auth.Group'),
        ),
    ]
