# Generated by Django 2.2.9 on 2020-09-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0023_responsavelcategoria'),
        ('perfil', '0037_unidade_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidade',
            name='responsaveis_categoria',
            field=models.ManyToManyField(to='chamados.ResponsavelCategoria'),
        ),
    ]
