# Generated by Django 3.0.3 on 2020-03-24 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('re_funcionario', models.CharField(max_length=5, verbose_name='RE')),
                ('nome', models.CharField(max_length=55, verbose_name='Nome do Funcionário')),
                ('centro_de_custo', models.CharField(max_length=6)),
                ('ramal', models.CharField(max_length=4)),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email Funcionário')),
            ],
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('', ''), ('Benefícios', 'Benefícios'), ('Cargos e Salários', 'Cargos e Sálarios'), ('Férias', 'Férias'), ('Folha de Pagamento', 'Folha de Pagamento'), ('Ponto', 'Ponto'), ('Treinamento', 'Treinamento')], default='-----------------------', max_length=23)),
                ('nome', models.CharField(max_length=55, verbose_name='Nome do Funcionário')),
                ('texto', models.TextField(verbose_name='Descrição')),
                ('resposta', models.TextField(blank=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('finalizado', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='chamados.Funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='chamados.Unidade')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='funcionario',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funcionarios', to='chamados.Unidade'),
        ),
        migrations.AlterUniqueTogether(
            name='funcionario',
            unique_together={('re_funcionario', 'unidade')},
        ),
    ]
