# Generated by Django 2.2.9 on 2020-05-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
