# Generated by Django 3.0.4 on 2020-06-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='data',
            field=models.DateTimeField(),
        ),
    ]
