# Generated by Django 3.0.4 on 2020-06-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0002_auto_20200610_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
