# Generated by Django 2.2.1 on 2020-03-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0002_auto_20200324_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='data_finalizada',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Finalizada '),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='centro_de_custo',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Funcionário'),
        ),
    ]
