# Generated by Django 3.0.4 on 2020-05-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0002_auto_20200507_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='data',
            field=models.DateTimeField(),
        ),
    ]
