# Generated by Django 3.0.4 on 2020-03-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0003_auto_20200326_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='categoria',
            field=models.CharField(choices=[('', ''), ('Benefícios', 'Benefícios'), ('Cargos e Salários', 'Cargos e Sálarios'), ('Férias', 'Férias'), ('Folha de Pagamento', 'Folha de Pagamento'), ('Ponto', 'Ponto'), ('Treinamento', 'Treinamento')], default='--------------------------------', max_length=23),
        ),
    ]
