# Generated by Django 3.0.4 on 2020-05-13 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0003_auto_20200513_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='upload_arquivo',
            field=models.FileField(blank=True, upload_to='documents/%Y/%m/%d\\'),
        ),
    ]
