# Generated by Django 2.2.9 on 2020-06-25 17:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0003_auto_20200610_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
            ],
            options={
                'verbose_name': 'Campo',
                'verbose_name_plural': 'Campos',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ModeloFormulario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
            ],
            options={
                'verbose_name': 'Modelo de Formulários',
                'verbose_name_plural': 'Modelos de Formulários',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ModeloFormularioCampo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelo_formulario', to='chamados.Campo', verbose_name='Campos')),
                ('modelo_formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelo_formulario', to='chamados.ModeloFormulario', verbose_name='Formulário')),
            ],
            options={
                'verbose_name': 'Formulário e Campo',
                'verbose_name_plural': 'Formulários e Campos',
                'ordering': ['-campo__nome'],
                'unique_together': {('modelo_formulario', 'campo')},
            },
        ),
        migrations.AddField(
            model_name='modeloformulario',
            name='campo',
            field=models.ManyToManyField(related_name='campo', through='chamados.ModeloFormularioCampo', to='chamados.Campo'),
        ),
    ]
