# Generated by Django 3.0.4 on 2020-05-13 22:44

import chamados.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0004_auto_20200513_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='upload_arquivo',
            field=models.FileField(blank=True, upload_to=chamados.models.update_filename),
        ),
    ]
