# Generated by Django 3.0.4 on 2020-04-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0004_auto_20200327_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='upload_arquivo',
            field=models.FileField(blank=True, upload_to='documents/%Y/%m/%d'),
        ),
    ]
