# Generated by Django 3.0.4 on 2020-04-07 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
        ('chamados', '0005_ticket_upload_arquivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='unidade',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='perfil.Funcionario'),
        ),
        migrations.DeleteModel(
            name='Funcionario',
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
        migrations.DeleteModel(
            name='Unidade',
        ),
    ]
