# Generated by Django 2.2.9 on 2020-06-25 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0005_campo_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='campo',
            name='valor_campo',
            field=models.CharField(default=1, max_length=250, verbose_name='Valor do Campo'),
            preserve_default=False,
        ),
    ]
