# Generated by Django 3.0.4 on 2020-05-19 18:27

import chamados.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0005_auto_20200513_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='nome',
            field=models.CharField(max_length=55, verbose_name='Funcionário : '),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='texto',
            field=models.TextField(verbose_name='Descrição : '),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='upload_arquivo',
            field=models.FileField(blank=True, upload_to=chamados.models.update_filename, verbose_name='Anexar Arquivo : '),
        ),
    ]
