# Generated by Django 3.0.4 on 2020-05-19 18:52

import chamados.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0006_auto_20200519_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='data_finalizada',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Finalizada : '),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='upload_arquivo',
            field=models.FileField(blank=True, upload_to=chamados.models.update_filename, verbose_name='Anexar Arquivos : '),
        ),
    ]
