# Generated by Django 2.2.9 on 2020-06-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0006_campo_valor_campo'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeloformulariocampo',
            name='texto',
            field=models.TextField(default=1, verbose_name='Descrição : '),
            preserve_default=False,
        ),
    ]
