# Generated by Django 2.2.9 on 2020-06-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0008_auto_20200626_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campo',
            name='valor_campo',
        ),
        migrations.AddField(
            model_name='modeloformulariocampo',
            name='valor_campo',
            field=models.CharField(default=1, max_length=250, verbose_name='Valor do Campo'),
            preserve_default=False,
        ),
    ]
