# Generated by Django 2.2.9 on 2020-06-26 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0009_auto_20200626_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='texto',
        ),
        migrations.AddField(
            model_name='modeloformulario',
            name='subcategoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='modelo_formulario', to='chamados.SubCategoria'),
            preserve_default=False,
        ),
    ]
