# Generated by Django 3.0.4 on 2020-05-26 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0009_auto_20200521_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='categoria',
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='chamados.Categoria')),
            ],
        ),
    ]
