# Generated by Django 3.0.4 on 2020-05-26 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0010_auto_20200526_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='subcategoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='chamados.SubCategoria'),
            preserve_default=False,
        ),
    ]
