# Generated by Django 2.2.9 on 2020-06-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0011_auto_20200626_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeloformulario',
            name='texto',
            field=models.TextField(null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='modeloformulariocampo',
            name='valor_campo',
            field=models.CharField(blank=True, max_length=250, verbose_name='Valor do Campo'),
        ),
    ]
