# Generated by Django 2.2.9 on 2020-06-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0012_auto_20200626_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='texto',
            field=models.TextField(default=1, verbose_name='Descrição'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modeloformulario',
            name='texto',
            field=models.TextField(null=True, verbose_name='Observação'),
        ),
    ]
