# Generated by Django 2.2.9 on 2020-06-26 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0013_auto_20200626_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modeloformulario',
            name='texto',
        ),
    ]
