# Generated by Django 2.2.9 on 2020-06-26 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0014_remove_modeloformulario_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeloformulario',
            name='texto',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modeloformulariocampo',
            name='texto',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
    ]
