# Generated by Django 2.2.9 on 2020-06-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0015_auto_20200626_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeloformulariocampo',
            name='texto',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
