# Generated by Django 2.2.9 on 2020-06-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0016_auto_20200626_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modeloformulariocampo',
            name='texto',
        ),
        migrations.AlterField(
            model_name='modeloformulario',
            name='texto',
            field=models.TextField(blank=True, verbose_name='Observação'),
        ),
    ]
