# Generated by Django 2.2.9 on 2020-06-26 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0017_auto_20200626_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeloformulario',
            name='ticket',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='modelo_formulario', to='chamados.Ticket'),
            preserve_default=False,
        ),
    ]
