# Generated by Django 2.2.9 on 2020-06-26 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0019_auto_20200626_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='modelo_formulario',
        ),
    ]
