# Generated by Django 2.2.9 on 2020-06-26 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0020_remove_ticket_modelo_formulario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modeloformulario',
            name='campo',
        ),
        migrations.RemoveField(
            model_name='modeloformulario',
            name='subcategoria',
        ),
        migrations.AlterUniqueTogether(
            name='modeloformulariocampo',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='modeloformulariocampo',
            name='campo',
        ),
        migrations.RemoveField(
            model_name='modeloformulariocampo',
            name='modelo_formulario',
        ),
        migrations.DeleteModel(
            name='Campo',
        ),
        migrations.DeleteModel(
            name='ModeloFormulario',
        ),
        migrations.DeleteModel(
            name='ModeloFormularioCampo',
        ),
    ]
