# Generated by Django 2.2.9 on 2020-07-10 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0023_customlogentry'),
        ('chamados', '0021_auto_20200626_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_mensagem', models.DateTimeField()),
                ('mensagem', models.TextField(blank=True, null=True, verbose_name='Mensagem :')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historico', to='perfil.Funcionario')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='chamados.Ticket')),
            ],
        ),
    ]
