# Generated by Django 2.2.9 on 2020-09-16 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0037_unidade_grupo'),
        ('chamados', '0022_historicoticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponsavelCategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsavel', to='perfil.Funcionario')),
                ('subcategoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsavel', to='chamados.SubCategoria')),
            ],
        ),
    ]
