# Generated by Django 2.2.9 on 2020-10-06 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0040_auto_20200922_1150'),
        ('chamados', '0023_responsavelcategoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsavelcategoria',
            name='responsavel_link',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='responsavel', to='perfil.Funcionario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='responsavelcategoria',
            name='responsavel',
            field=models.IntegerField(verbose_name='Responsável'),
        ),
    ]
