# Generated by Django 2.2.9 on 2020-10-07 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0024_auto_20201006_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsavelcategoria',
            name='responsavel_link',
        ),
        migrations.AlterField(
            model_name='responsavelcategoria',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsavel', to='perfil.Funcionario'),
        ),
    ]
