# Generated by Django 2.2.9 on 2020-10-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0025_auto_20201007_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategoria',
            name='categoria',
        ),
        migrations.AddField(
            model_name='categoria',
            name='subcategoria',
            field=models.ManyToManyField(to='chamados.SubCategoria'),
        ),
    ]
